config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Take advantage of shallow routing wherever possible:
  # :index, :new, :create should be nested with parent resource
  # :show, :edit, :update, :destroy should be unnested

  root                     'static_pages#home'
  get   'about'        =>  'static_pages#about'
  get   'contact'      =>  'static_pages#contact'
  get   'develop'      =>  'static_pages#develop'

  ####################################################
  # Profiles
  # devise routes for authentication
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'registrations' }
  resources :profiles, controller: 'users' do
    resources :resumes, only: %i[index create destroy]
    get 'settings'
  end

  ####################################################
  # Organizations
  resources :organizations do
    member do
      get 'approve'
      get 'withdraw'
      get 'archive'
    end
    collection do
      get 'admin'
      get 'manage'
      get 'user'
      post 'admin', to: 'organizations#filter'
      post 'manage', to: 'organizations#filter_manage'
      post 'organizations', to: 'organizations#filter_index'
      post 'user', to: 'organizations#filter_user'
    end
    resources :jobs, only: %i[new create]
  end

  ####################################################
  # Jobs
  resources :jobs, only: %i[show edit update destroy] do
    member do
      get 'assign'
      post 'create_position'
      put 'add_user'
    end
  end

  resources :job_postings do
    resources :job_posting_questions, only: %i[index create update destroy]
    resources :job_applications, only: %i[index new create] do
      resource :job_posting_answers, only: %i[new create]
    end
    member do
      get 'approve'
      get 'withdraw'
      get 'interview'
      get 'close'
      get 'reopen'
    end
    collection do
      get 'select'
      get 'admin'
      get 'manage'
      post 'admin', to: 'job_postings#filter'
      post 'manage', to: 'job_postings#filter_manage'
      post 'job_postings', to: 'job_postings#filter_index'
    end
  end

  resources :job_applications, only: %i[show update destroy] do
    resource :job_posting_answers, only: %i[edit update destroy]
    resources :interviews, only: [:new]
    member do
      get 'select_resume'
      patch 'update_resume'
      get 'finalize'
      get 'hire'
      get 'decline'
    end
    collection do
      get 'user'
      post 'user', to: 'job_applications#filter_user'
    end
  end

  resources :interviews, only: %i[create edit update] do
    collection do
      get 'manage'
      get 'admin'
    end
  end

  resources :positions do
    collection do
      get 'admin'
    end
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home
    # p request.headers
    @email = request.headers['HTTP_EMAIL']
    @firstname = request.headers['givenName']
    @lastname = request.headers['surname']
    @job_postings = JobPosting.where(status: 'open').order(:updated_at).reverse_order.limit(3)
    @job_applications = JobApplication.where(user_id: current_user.id, status: %w[submitted draft]).order(:updated_at).reverse_order.limit(5)
    @job_interviews = Interview.includes(:job_application).where(job_applications: { user_id: current_user.id, status: 'interview_scheduled' }).limit(5)
  end

  def about; end

  def contact; end

  def credits; end
end

app/views/static_pages/about.html.erb
<% content_for :title, "About" %>

<div class="container container-lg">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-heading">
          <div class="text-center">
            <h3 class="text-bold">About EngSoc Dash</h3>
          </div>
        </div>
        <div class="card-body text-center">
          <div class="container container-xs reader-block">
            <p>
              The Queen's EngSoc Dash is a student-lead initative to modernize and revitalize the modern tools that are accessible for use by Queen's students.
            </p>
            <p>
              The idea was initially conceived in order to replace the outdated EngSoc Apply system, and to eventually serve as the one stop hub for all things related to EngSoc.
            </p>
            <p>
              The Dash is an ambitious <a href="https://github.com/RobertWSaunders/engsoc-dash/wiki/Project-Proposal">project</a> that requires your support to become a reality. Contact your EngSoc council to show support for further expansion of the project.
            </p>
          </div>
        </div>
        <div class="card-body p-xl mt-lg">
          <hr>
          <%= render "shared/slack" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% content_for :title, "Contact" %>

<div class="container container-lg">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-heading">
          <div class="text-center pb-lg">
            <h3 class="text-bold">Contact</h3>
            <p>
              The best and quickest way to reach the right people is through the <a href="https://join.slack.com/t/engsoc-dash/signup?x=x-223666223958-222892608962">Slack channel</a>.
              <br>These are the channels or people you want to reach out to for support based on your needs.
            </p>
          </div>
        </div>
        <div class="card-body text-center">
          <div class="row">
            <div class="col-sm-6">
              <div class="card b">
                <div class="card-body text-center bg-info">
                  <h3 class="mv-lg"><a href="https://engsoc-dash.slack.com/messages/support/" style="color: inherit;">#support</a></span></h3>
                </div>
                <div class="card-body text-center">
                  <p class="mb-lg"><span>Admin Requests</span></p>
                  <p class="mb-lg"><span>System Notifications</span></p>
                  <p class="mb-lg"><span>Any Questions</span></p>
                </div>
                <div class="card-body text-center bt"><a href="" class="btn btn-default btn-flat" class="contact-link">#support</a></div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="card b">
                <div class="card-body text-center bb bg-deep-purple-500">
                  <h3 class="mv-lg"><a href="https://engsoc-dash.slack.com/messages/general/" style="color: inherit;" class="contact-link">#general</a></span></h3>
                </div>
                <div class="card-body text-center">
                  <p class="mb-lg"><span>General Discussions</span></p>
                  <p class="mb-lg"><span>Advertising Positions</span></p>
                  <p class="mb-lg"><span>Reporting Bugs</span></p>
                </div>
                <div class="card-body text-center bt"><a href="" class="btn btn-default btn-flat">#general</a></div>
              </div>
            </div>
          </div>
          <div class="row mt-xl">
            <p>If you aren't able to access reach us at the above methods, you can send us an email at <a href="">email@engsoc.queensu.ca</a>,
              <br /> but it is highly recommended that you reach us through Slack.</p>
          </div>
        </div>
        <div class="card-body p-xl mt-lg">
          <hr>
          <%= render "shared/slack" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/develop.html.erb
<% content_for :title, "Development" %>

<div class="container container-lg">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-heading">
          <div class="text-center">
            <h3 class="text-bold">Development</h3>
          </div>
        </div>
        <div class="card-body text-center">
          <div class="container container-xs reader-block">
            <h4 class="text-bold">Release Notes</h4>
            <p>
              The current version is 1.0.0.
              <br> View the <a href="/changes">full change log</a>.
            </p>
          </div>
          <div class="container container-xs reader-block">
            <h4 class="text-bold">Contribute</h4>
            <p>
              The EngSoc Dash is open source under the <a href="https://en.wikipedia.org/wiki/MIT_License">MIT License</a>, and is publicly hosted on <a href="https://github.com/RobertWSaunders/engsoc-dash">Github</a>.
            </p>
            <p>
              If you want to get involved, you can! Simply open a pull-request. You can <a href="https://engsoc-dash.slack.com/messages/@peter/">contact</a> the lead developer for more information, or read the introductory <a href="https://github.com/RobertWSaunders/engsoc-dash/wiki/Developer-Guide">developer guide</a>.
            </p>
          </div>
          <div class="container container-xs reader-block">
            <h4 class="text-bold">Credit</h4>
            <p>
              The Dash was originally conceived and created by Robert Saunders and Peter Ju during their undergraduate studies at Queen's.
            </p>
            <p>
              The project was first publicly demoed during the last EngSoc council of the 2016 - 17 academic year, with much appreciated support from the incoming directors. The project could not have gotten this far without their support.
            </p>
          </div>
        </div>
        <div class="card-body p-xl mt-lg">
          <hr>
          <%= render "shared/slack" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% content_for :title, "EngSoc Dash" %>

<div class="content-heading bg-white">
  <div class="row">
    <div class="col-sm-9">
      <h4 class="m0 text-thin">Welcome to the Engineering Society Dashboard</h4>
    </div>
  </div>
</div>

<div class="container container-fluid">
  <div class="row">
    <div class="col-xs-12 col-lg-6">
      <div class="card p">
        <div class="card-heading">
          <div class="card-title">Job Applications</div>
          <small>View or continue job applications</small>
          <div class="pull-right">
            <%= link_to "View All", user_job_applications_path %>
          </div>
        </div>
        <div class="card-body">
          <table class="table table-hover table-fixed va-middle">
            <tbody>
              <% if @job_applications.any? %>
                <% @job_applications.each do |app| %>
                <tr class="msg-display">
                  <td class="wd-xs">
                    <%= status_label_application(app) %>
                  </td>
                  <td>
                    <strong><%= link_to app.job_posting.title, app.job_posting %></strong> <% if app.status == "draft" %> | <i><%= link_to "Continue Application", new_job_posting_job_application_path(:job_posting_id => app.job_posting.id, :id => app.id) %></i><% end %>
                    <br>
                    <small><%= link_to app.job_posting.job.organization.name, app.job_posting.job.organization %></small>
                  </td>
                </tr>
                <% end %>
              <% else %>
                <p class="text-center">
                  No Job Applications
                </p>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-lg-6">
      <div class="card p">
        <div class="card-heading">
          <div class="card-title">Job Interviews</div>
          <small>You've got this, don't worry!</small>
          <div class="pull-right">
            <%= link_to "View All", user_job_applications_path %>
          </div>
        </div>
        <div class="card-body">
          <table class="table table-hover table-fixed va-middle">
            <tbody>
              <% if @job_interviews.any? %>
                <% @job_interviews.each do |int| %>
                <tr class="msg-display">
                  <td class="wd-sm">
                    <%= status_label_application(int.job_application) %>
                  </td>
                  <td>
                    <strong><%= link_to int.job_application.job_posting.title, int.job_application.job_posting %></strong>
                    <br>
                    <small><%= link_to int.job_application.job_posting.job.organization.name, int.job_application.job_posting.job.organization %></small>
                    <br>
                    <%= int.start_time.strftime("%b %e, %l:%M %p") %> - <%= int.end_time.strftime("%b %e, %l:%M %p") %>
                  </td>
                </tr>
                <% end %>
              <% else %>
                <p class="text-center">
                  No scheduled Interviews
                </p>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-lg-12">
          <div class="card p">
            <div class="card-heading">
              <div class="card-title">Newest Job Postings</div>
              <small>Get involved, gain experience</small>
              <div class="pull-right">
                <%= link_to "View All", job_postings_path %>
              </div>
            </div>
            <div class="card-body">
              <table class="table table-hover table-fixed va-middle">
                <tbody>
                  <% @job_postings.each do |posting| %>
                  <tr class="msg-display">
                    <td class="wd-xs">
                      <%= status_label(posting) %>
                    </td>
                    <td>
                      <strong><%= link_to posting.title, posting %></strong>
                      <br>
                      <small><%= link_to posting.job.organization.name, posting.job.organization %></small>
                    </td>
                    <td>
                      <small>Deadline:</small>
                      <br><%= posting.deadline.strftime("%A, %b %d, %Y") %><% if posting.deadline.future? %> | <%= distance_of_time_in_words(Time.now, posting.deadline) %><% end %>
                    </td>
                    <td>
                      <small>Last Updated:</small>
                      <br><%= posting.updated_at.strftime("%A, %b %d, %Y, %l:%M %p") %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-xs-12">
      <!-- Activity feed-->
      <!-- <div class="card">
        <div class="card-heading">
          <div class="pull-right dropdown">
            <button type="button" data-toggle="dropdown" class="btn btn-default btn-flat btn-flat-icon"><em class="ion-android-more-vertical"></em></button>
            <ul role="menu" class="dropdown-menu md-dropdown-menu dropdown-menu-right">
              <li><a href="">Last 30 days</a></li>
              <li><a href="">Last week</a></li>
              <li><a href="">Last year</a></li>
            </ul>
          </div>
          <div class="card-title">News Feed</div><small>Engineering Society news</small>
        </div>
        <div class="card-body bb">
          <p class="pull-left mr"><a href=""><%= image_tag "centric/user/02.jpg", class: "img-circle thumb32" %></a></p>
          <div class="oh">
            <p><strong class="spr">Adam</strong><span class="spr">posted in</span><a href="">Material</a></p>
            <p class="bl pl"><i>That's awesome!</i></p>
            <div class="clearfix">
              <div class="pull-left text-muted"><em class="ion-android-time mr-sm"></em><span>2 hours ago</span></div>
            </div>
          </div>
        </div>
        <div class="card-body bb">
          <p class="pull-left mr"><a href=""><%= image_tag "centric/user/04.jpg", class: "img-circle thumb32" %></a></p>
          <div class="oh">
            <p><strong class="spr">Dora</strong><span>added a new task</span></p>
            <p><em class="ion-calendar icon-fw"></em><a href="">Start migration</a></p>
            <div class="clearfix">
              <div class="pull-left text-muted"><em class="ion-android-time mr-sm"></em><span>3 hours ago</span></div>
              <div class="pull-right"><span>2</span><em class="ion-star ml-sm text-warning"></em></div>
            </div>
          </div>
        </div>
        <div class="card-body bb">
          <p class="pull-left mr"><a href=""><%= image_tag "centric/user/03.jpg", class: "img-circle thumb32" %></a></p>
          <div class="oh">
            <p><strong class="spr">Kathryn</strong><span class="spr">published</span><a href="">Trip</a></p>
            <div class="clearfix">
              <div class="pull-left text-muted"><em class="ion-android-time mr-sm"></em><span>4 hours ago</span></div>
              <div class="pull-right"><span>2</span><em class="ion-ios-heart ml-sm text-danger"></em></div>
            </div>
          </div>
        </div>
        <div class="card-body bb">
          <p class="pull-left mr"><a href=""><%= image_tag "centric/user/05.jpg", class: "img-circle thumb32" %></a></p>
          <div class="oh">
            <p><strong class="spr">Daniel</strong><span class="spr">joined to</span><a href="">Group</a></p>
            <div class="clearfix">
              <div class="pull-left text-muted"><em class="ion-android-time mr-sm"></em><span>yesterday</span></div>
            </div>
          </div>
        </div>
        <div class="card-body bb">
          <p class="pull-left mr"><a href=""><%= image_tag "centric/user/06.jpg", class: "img-circle thumb32" %></a></p>
          <div class="oh">
            <p><strong class="spr">Leroy Day</strong><span class="spr">wakes up!</span></p>
            <p class="bl pl"><i>That's awesome!</i></p>
            <div class="clearfix">
              <div class="pull-left text-muted"><em class="ion-android-time mr-sm"></em><span>2 weeks ago</span></div>
            </div>
          </div>
        </div><a href="" class="card-footer btn btn-flat btn-default"><small class="text-center text-muted lh1">See more activities</small></a>
      </div>
      -->
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-4">
          <div class="card p">
            <div class="card-body">
              <h4><em class="ion-ios-people icon-fw"></em> Organizations</h4>
              <ul class="list-unstyled text-thin">
                <li class="p"><%= link_to "All Organizations", organizations_path %></li>
                <li class="p"><%= link_to "My Organizations", user_organizations_path %></li>
                <li class="p"><%= link_to "Register a New Organization" %></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card p">
            <div class="card-body">
              <h4><em class="ion-ios-list icon-fw"></em> Job Postings</h4>
              <ul class="list-unstyled text-thin">
                <li class="p"><%= link_to "All Open Postings", job_postings_path %></li>
                <li class="p"><%= link_to "My Applications", user_job_applications_path %></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card p">
            <div class="card-body">
              <h4><em class="ion-ios-person icon-fw"></em> Profile</h4>
              <ul class="list-unstyled text-thin">
                <li class="p"><%= link_to "Profile", profile_path(current_user) %></li>
                <li class="p"><%= link_to "Edit Profile", edit_profile_path(current_user) %></li>
                <li class="p"><%= link_to "Resumes", profile_resumes_path(current_user) %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render "shared/slack" %>

app/views/static_pages/settings.html.erb
<% content_for :title, "Settings" %>

<div class="container container-lg">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="card">
        <div class="card-heading">
          <h4 class="text-bold">
            Email Notifications</h4>
        </div>
        <div class="card-body">
          <%= form_for @user, :html => {:class => 'form-horizontal'} do |f| %>
            <fieldset class="last-child">
              <div class="form-group">
                <%= f.label "Enable", class: "col-sm-1 control-label" %>
                <div class="col-sm-11">
                  <%= f.check_box :emailNotifications %>
                </div>
              </div>
            </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>