config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Take advantage of shallow routing wherever possible:
  # :index, :new, :create should be nested with parent resource
  # :show, :edit, :update, :destroy should be unnested

  root                     'static_pages#home'
  get   'about'        =>  'static_pages#about'
  get   'contact'      =>  'static_pages#contact'
  get   'develop'      =>  'static_pages#develop'

  ####################################################
  # Profiles
  # devise routes for authentication
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'registrations' }
  resources :profiles, controller: 'users' do
    resources :resumes, only: %i[index create destroy]
    get 'settings'
  end

  ####################################################
  # Organizations
  resources :organizations do
    member do
      get 'approve'
      get 'withdraw'
      get 'archive'
    end
    collection do
      get 'admin'
      get 'manage'
      get 'user'
      post 'admin', to: 'organizations#filter'
      post 'manage', to: 'organizations#filter_manage'
      post 'organizations', to: 'organizations#filter_index'
      post 'user', to: 'organizations#filter_user'
    end
    resources :jobs, only: %i[new create]
  end

  ####################################################
  # Jobs
  resources :jobs, only: %i[show edit update destroy] do
    member do
      get 'assign'
      post 'create_position'
      put 'add_user'
    end
  end

  resources :job_postings do
    resources :job_posting_questions, only: %i[index create update destroy]
    resources :job_applications, only: %i[index new create] do
      resource :job_posting_answers, only: %i[new create]
    end
    member do
      get 'approve'
      get 'withdraw'
      get 'interview'
      get 'close'
      get 'reopen'
    end
    collection do
      get 'select'
      get 'admin'
      get 'manage'
      post 'admin', to: 'job_postings#filter'
      post 'manage', to: 'job_postings#filter_manage'
      post 'job_postings', to: 'job_postings#filter_index'
    end
  end

  resources :job_applications, only: %i[show update destroy] do
    resource :job_posting_answers, only: %i[edit update destroy]
    resources :interviews, only: [:new]
    member do
      get 'select_resume'
      patch 'update_resume'
      get 'finalize'
      get 'hire'
      get 'decline'
    end
    collection do
      get 'user'
      post 'user', to: 'job_applications#filter_user'
    end
  end

  resources :interviews, only: %i[create edit update] do
    collection do
      get 'manage'
      get 'admin'
    end
  end

  resources :positions do
    collection do
      get 'admin'
    end
  end
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  scope :job_department, ->(job_department) { joins(:organization).where(organizations: { department: job_department }) }

  # Relationships
  # a job belongs to an organization
  belongs_to :organization, foreign_key: :organization_id
  # a job job belongs to a user
  # belongs_to :user, :foreign_key => :user_id
  has_many :users, through: :positions
  has_many :positions, dependent: :destroy
  has_one :job_posting, foreign_key: :job_id, dependent: :destroy

  # Validations
  # make sure the organization id is present
  validates :organization_id, presence: true
  # make sure the user id is present and unique
  # validates :user_id, presence: true, :uniqueness => { :scope => :organization_id }
  # make sure the title is present
  validates :title, presence: true, uniqueness: { case_sensitive: false, scope: :organization_id }
  validates :description, presence: true, length: { minimum: 15, maximum: 4000 }

  # organizations model has the same status enum
  enum status: %i[waiting_approval active archived]

  enum role: %i[regular management admin]
  enum job_type: %i[volunteer part_time full_time]

  accepts_nested_attributes_for :users, :positions
  # :organization
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  include UserHelper

  load_and_authorize_resource

  skip_authorize_resource only: %i[new create]

  before_action :set_job, only: %i[show assign destroy edit update]

  # GET /organizations/:organization_id/jobs/new
  def new
    @job = Job.new
    @organization = Organization.find(params[:organization_id])
    unless superadmin?(current_user) || managed_orgs(current_user).include?(@organization)
      flash[:warning] = "Can't create a new job for an organization you don't manage."
      redirect_back(fallback_location: organizations_path)
    end
  end

  # POST /organizations/:organization_id/jobs/new
  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:success] = 'Job Successfully Created!'
      redirect_to assign_job_path(@job.id)
    else
      flash.keep[:danger] = 'Could Not Save Job!'
      flash[:danger] << '<li>' + @job.errors.full_messages.join('</li><li>')
      flash[:danger] << '</ul>'
      redirect_to new_organization_job_path
    end
  end

  # GET /jobs/:id
  def show
    @organization = @job.organization
    if @organization.status != 'active' && !superadmin?(current_user)
      flash[:warning] = 'The job ' + @job.title + ' cannot be viewed because its organization, ' + @organization.name + ' is not active.'
      redirect_back(fallback_location: organizations_path)
    end
    # @users = @job.user
  end

  # GET /jobs/:id/edit
  def edit; end

  # PUT /jobs/:id
  def update
    if @job.update_attributes(job_params)
      flash[:success] = 'Job Updated'
      redirect_to job_path(@job)
    else
      render 'edit'
    end
  end

  # DELETE /jobs/:id
  def destroy
    @job.destroy
    redirect_to organization_path(@job.organization_id)
  end

  # GET /jobs/:id/assign
  def assign; end

  # POST /jobs/:id/create_position
  def create_position
    pos_params = position_params
    usr = User.find_by(email: pos_params[:user_id].downcase)
    if usr.blank?
      flash.keep[:warning] = 'Could not find a user by that email, make sure you have spelt the email right, and that they have signed onto DASH at least once, and try again.'
      redirect_back(fallback_location: user_organizations_path)
    else
      pos_params[:user_id] = usr.id
      @position = Position.new(pos_params)
      if @position.save
        user = User.find(@position.user_id)
        job = Job.find(@position.job_id)
	flash[:success] = user.first_name.to_s + ' ' + user.last_name.to_s + ' assigned as ' + job.title.to_s + ' from ' + @position.start_date.to_date.to_s + ' to ' + @position.end_date.to_date.to_s
        redirect_to :back
      else
        flash.keep[:danger] = 'Could Not Save Position'
        flash[:danger] << '<li>' + @position.errors.full_messages.join('</li><li>')
        flash[:danger] << '</ul>'
        redirect_to assign_job_path
      end
    end
  end

  # PUT /jobs/:id/add_user
  def add_user
    user = User.find(job_params[:user_id])
    @job.users << user
  end

  private

  def job_params
    params.require(:job).permit(:title, :organization_id, :description, :role, :job_type, user_ids: [])
  end

  def position_params
    params.require(:position).permit(:job_id, :user_id, :start_date, :end_date)
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/views/jobs/_job.html.erb
<tr>
  <td><%= link_to job.title, job_path(:id => job.id) %></td>
  <td>
    <% if job.positions.any? && job.positions.first.active? %>
      Currently Filled
    <% elsif job.job_posting.present? && job.job_posting.active? %>
      <%= link_to "Taking Applications", job_posting_path(id: job.job_posting.id) %>
    <% end %>
  </td>
  <td>
    <% if job.role == "management" %>
      Managerial Position
    <% elsif job.role == "admin" %>
      Administration Position
    <% elsif job.role == "regular" %>
      General Member Position
    <% end %>
  </td>
  <td>
    <%= job.job_type.titleize %>
  </td>
  <td>
    <% if can? :manage, job %>
      <%= link_to edit_job_path(job.id), class: "btn btn-sm btn-warning" do %>
        <em class="ion-edit"></em>
      <% end %>
      <% if can? :manage, :all %>
        <%= link_to job, method: :delete, data: { confirm: "Are you sure you want to delete this job? It is highly recommended you do not delete jobs, and instead keep the job without any active positions." }, class: "btn btn-sm btn-danger" do %>
          <em class="ion-trash-a"></em>
        <% end %>
      <% end %>
      <%= link_to assign_job_path(job.id), class: "btn btn-sm btn-primary" do %>
        <em class="ion-android-person-add"></em>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/jobs/_job_dropdown.html.erb
<% if can? :manage, job %>
  <div class="pull-right dropdown">
    <button type="button" data-toggle="dropdown" class="btn btn-default btn-flat btn-flat-icon"><em class="ion-android-more-vertical"></em></button>
    <ul role="menu" class="dropdown-menu md-dropdown-menu dropdown-menu-right">
      <li>
        <%= link_to "Edit Job", edit_job_path(job.id) %>
      </li>
      <li>
        <%= link_to "Delete Job", method: :delete, data: { confirm: "Are you sure?" } %>
      </li>
  </div>

<% end %>

app/views/jobs/_job_form.html.erb
<% if action_name == 'new' %>

  <%= form_for([@organization, @job], :html => {:class => 'form-horizontal'}) do |f| %>
    <!-- render any error messages -->
    <%= render 'shared/job_error_messages' %>

    <!-- hidden field for the organization id -->
    <% if defined? @job.organization.id %>
      <%= f.hidden_field :organization_id, :value => @job.organization.id %>
    <% else %>
      <%= f.hidden_field :organization_id, :value => @organization.id %>
    <% end %>

    <!-- form fields -->
    <!-- organization -->
    <fieldset class="last-child">
      <div class="form-group">
        <label class="col-sm-1 control-label">Organization</label>
        <div class="col-sm-11">
          <input type="text" placeholder="<%= @organization.name %>" disabled="" class="form-control">
        </div>
      </div>
    </fieldset>

    <!-- title -->
    <fieldset class="last-child">
      <div class="form-group">
        <%= f.label :title, "Job Title",class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
    </fieldset>

    <!-- description -->
    <fieldset>
      <div class="form-group">
        <%= f.label :description, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_area :description, class: 'form-control', rows: "8", style: 'resize:none' %>
        </div>
      </div>
    </fieldset>

    <!-- role -->
    <fieldset>
      <div class="row">
      <%= f.label :role, "Job Role",class: "col-sm-1 control-label" %>
        <!-- only admins are able to set the status -->
        <div class="col-sm-11">
          <% if superadmin?(current_user) %>
            <%= f.select :role, Job.roles.keys.map { |w| [w.titleize, w] }, {}, {class: "form-control"} %>
          <% else %>
            <%= f.select :role, [["Regular", "regular"],["Management", "management"]], {}, {class: "form-control"} %>
          <% end %>
        </div>
      </div>
    </fieldset>

    <!-- job type -->
    <fieldset class="last-child">
      <div class="row">
        <%= f.label :job_type, "Job Type",class: "col-sm-1 control-label" %>
          <!-- only admins are able to set the status -->
          <div class="col-sm-11">
            <%= f.select :job_type, Job.job_types.keys.map { |w| [w.titleize, w] }, {}, {class: "form-control"} %>
          </div>
      </div>
    </fieldset>
    <hr>

    <!-- submit button -->

    <%= f.submit "Create Job", class: "btn btn-primary btn-block" %>
    <%= link_to "Cancel",root_path, class: "btn btn-inverse btn-block" %>
  <% end %>

<% else %>

  <%= form_for @job, :html => {:class => 'form-horizontal'} do |f| %>
    <!-- render any error messages -->
    <%= render 'shared/job_error_messages' %>

    <!-- hidden field for the organization id -->
    <% if defined? @job.organization.id %>
      <%= f.hidden_field :organization_id, :value => @job.organization.id %>
    <% else %>
      <%= f.hidden_field :organization_id, :value => @organization.id %>
    <% end %>

    <!-- form fields -->
    <!-- organization -->
    <fieldset class="last-child">
      <div class="form-group">
        <label class="col-sm-1 control-label">Organization</label>
        <div class="col-sm-11">
          <input type="text" placeholder="<%= @job.organization.name %>" disabled="" class="form-control">
        </div>
      </div>
    </fieldset>

    <!-- title -->
    <fieldset class="last-child">
      <div class="form-group">
        <%= f.label :title, "Job Title",class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
    </fieldset>

    <!-- description -->
    <fieldset>
      <div class="form-group">
        <%= f.label :description, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_area :description, class: 'form-control', rows: "8", style: 'resize:none' %>
        </div>
      </div>
    </fieldset>

    <!-- role -->
    <fieldset>
      <div class="row">
      <%= f.label :role, "Job Role",class: "col-sm-1 control-label" %>
        <!-- only admins are able to set the status -->
        <div class="col-sm-11">
          <% if can? :manage, :all %>
            <%= f.select :role, Job.roles.keys.map { |w| [w.titleize, w] }, {}, {class: "form-control"} %>
          <% else %>
            <%= f.select :role, [["Regular", "regular"],["Management", "management"]], {}, {class: "form-control"} %>
          <% end %>
        </div>
      </div>
    </fieldset>

    <!-- job type -->
    <fieldset class="last-child">
      <div class="row">
        <%= f.label :job_type, "Job Type",class: "col-sm-1 control-label" %>
          <div class="col-sm-11">
            <%= f.select :job_type, Job.job_types.keys.map { |w| [w.titleize, w] }, {}, {class: "form-control"} %>
          </div>
      </div>
    </fieldset>
    <hr>

    <!-- submit button -->

    <%= f.submit "Edit Job", class: "btn btn-primary btn-block" %>
    <%= link_to "Cancel",root_path, class: "btn btn-inverse btn-block" %>
  <% end %>

<% end %>

app/views/jobs/_job_list_manage_buttons.html.erb
<%= link_to edit_job_path(job.id), class: "btn btn-sm btn-warning" do %>
  <em class="ion-edit"></em>
<% end %>
<%= link_to job, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" do %>
  <em class="ion-trash-a"></em>
<% end %>
<%= link_to assign_job_path(job.id), class: "btn btn-sm btn-primary" do %>
  <em class="ion-android-person-add"></em>
<% end %>

app/views/jobs/_users_table.html.erb
<% if @job.positions.any? %>
  <div class="table-responsive mh">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Status</th>
          <th>Start Date</th>
          <th>End Date</th>
        </tr>
      </thead>
      <tbody>
        <% @job.positions.order(:start_date).reverse.each do |pos| %>
          <%= render pos %>
        <% end %>
      </tbody>
    </table>
    <p class="mh">
      Historical Total: <%= pluralize @job.positions.count, + @job.title %> worked for <%= @job.organization.name %>
    </p>
  </div>

<% else %>

  <div class="alert alert-warning mh mv">
    This position has no employment history and is currently vacant.
  </div>

<% end %>

app/views/jobs/assign.html.erb
<!-- page title -->
<% content_for :title, "Assign to Job" %>

<!-- page content -->
<div class="container-fluid container-lg">

  <div class="card">
    <div class="card-body">
      <h4>
        <%= link_to @job.title, @job %><br>
        <small><%= link_to @job.organization.name, @job.organization %></small>
      </h4>

      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" href="#history">Position History</a>
            </h4>
          </div>
          <div id="history" class="panel-collapse collapse">
            <%= render "users_table" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <p class="lead mv mh">
        Assign a User as <%= @job.title %>
      </p>
      <%= form_for(:position, :url => create_position_job_path, :html => {:class => 'form-horizontal'}) do |f| %>

        <%= f.hidden_field :job_id, :value => @job.id %>
        <hr>
        <fieldset>
          <%= f.label :Email, class: "col-sm-1 control-label" %>
          <div class="col-sm-11">
            <ul class="col-sm-11">
              <%= f.email_field :user_id %>
            </ul>
          </div>
        </fieldset>

        <fieldset>
          <div class="col-sm-11 col-sm-offset-1">
            <span class="help-block">
              Position Term Dates
            </span>
          </div>
          <div class="row">
            <%= f.label :start_date, class: "col-sm-1 control-label" %>
            <div class="col-sm-11 form-inline">
              <%= f.date_select :start_date, {"data-provide" => 'datepicker', :include_blank => true,:default => nil, start_year: Date.today.year, end_year: Date.today.year + 2}, {class: "form-control"} %>
            </div>
          </div>
          <div class="row mv">
            <%= f.label :end_date, class: "col-sm-1 control-label" %>
            <div class="col-sm-11 form-inline">
              <%= f.date_select :end_date, {"data-provide" => 'datepicker', :include_blank => true, :default => nil, start_year: Date.today.year, end_year: Date.today.year + 2}, {class: "form-control"} %>
            </div>
          </div>
        </fieldset>

        <%= f.submit "Create Position", class: "btn btn-flat btn-block btn-primary" %>
      <% end %>
    </div>
  </div>

  <% if !@job.job_posting.present? %>
    <%= link_to new_job_posting_path(:organization_id => @job.organization_id, :job_id => @job.id), class: "btn btn-flat btn-info" do %>
      <em class="ion-plus-round icon-fw"></em> Create Job Posting
    <% end %>
  <% else %>
    <%= link_to job_posting_path(@job.job_posting), class: "btn btn-flat btn-primary" do %>
      <em class="ion-ios-list icon-fw"></em> View Job Posting
    <% end %>
  <% end %>

  <%= link_to organization_path(@job.organization), class: "btn btn-flat btn-default pull-right" do %>
    <em class="ion-ios-arrow-back icon-fw"></em> Back to <%= @job.organization.name %>
  <% end %>

</div>

app/views/jobs/edit.html.erb
<!-- page title -->
<% content_for :title, "Edit Job" %>

<!-- page content -->
<div class="container-fluid container-lg">
  <div class="card">
    <div class="card-body">
      <!-- render the job form -->
      <%= render 'job_form' %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<!-- page title -->
<% content_for :title, "New Job" %>

<!-- page content -->
<div class="container-fluid container-lg">
  <div class="card">
    <div class="card-body">
      <!-- render the job form -->
      <%= render 'job_form' %>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<% content_for :title, "Job Information" %>

<div class="container container-lg">


<div class="card">
  <div class="card-body">
    <!-- render the dropdown-->
    <%= render 'job_dropdown', job: @job %>

    <p class="lead"><%= link_to @job.title, job_path(:id => @job.id) %></p>
    <hr />
    <p>
      Organization: <%= link_to @organization.name, @organization %>
    </p>
    <p>
      Job Type: <%= @job.job_type.titleize %>
    </p>
    <p>
      Role: <%= @job.role.titleize %>
    </p>
    <p>
      <%= simple_format(@job.description) %>
    </p>
  </div>
</div>

  <div class="card">
    <div class="card-body">
      <% if can? :manage, @job %>
        <%= link_to 'Assign Users to Job', assign_job_path(id: @job.id), class: "btn btn-flat btn-info pull-right mh" %>
      <% end %>  
      <% if @job.job_posting.present? %>
        <% if (@job.job_posting.status == "open") || (can? :manage, @job) %>
          <%= link_to 'View Job Posting', job_posting_path(id: @job.job_posting.id), class: "btn btn-flat btn-success pull-right mh" %>
        <% end %>
      <% else %>
        <% if can? :manage, @job %>
          <%= link_to 'Create Job Posting', new_job_posting_path(job_id: @job.id), class: "btn btn-flat btn-primary pull-right mh" %>
        <% end %>
      <% end %>
      <p class="lead">Position History</p>
      <div class="row" id="users">
        <%= render "users_table" %>
      </div>
    </div>
  </div>

  <%= link_to organization_path(@job.organization), class: "btn btn-flat btn-default pull-right" do %>
    <em class="ion-ios-arrow-back icon-fw"></em> Back to <%= @job.organization.name %>
  <% end %>
</div>