config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Take advantage of shallow routing wherever possible:
  # :index, :new, :create should be nested with parent resource
  # :show, :edit, :update, :destroy should be unnested

  root                     'static_pages#home'
  get   'about'        =>  'static_pages#about'
  get   'contact'      =>  'static_pages#contact'
  get   'develop'      =>  'static_pages#develop'

  ####################################################
  # Profiles
  # devise routes for authentication
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'registrations' }
  resources :profiles, controller: 'users' do
    resources :resumes, only: %i[index create destroy]
    get 'settings'
  end

  ####################################################
  # Organizations
  resources :organizations do
    member do
      get 'approve'
      get 'withdraw'
      get 'archive'
    end
    collection do
      get 'admin'
      get 'manage'
      get 'user'
      post 'admin', to: 'organizations#filter'
      post 'manage', to: 'organizations#filter_manage'
      post 'organizations', to: 'organizations#filter_index'
      post 'user', to: 'organizations#filter_user'
    end
    resources :jobs, only: %i[new create]
  end

  ####################################################
  # Jobs
  resources :jobs, only: %i[show edit update destroy] do
    member do
      get 'assign'
      post 'create_position'
      put 'add_user'
    end
  end

  resources :job_postings do
    resources :job_posting_questions, only: %i[index create update destroy]
    resources :job_applications, only: %i[index new create] do
      resource :job_posting_answers, only: %i[new create]
    end
    member do
      get 'approve'
      get 'withdraw'
      get 'interview'
      get 'close'
      get 'reopen'
    end
    collection do
      get 'select'
      get 'admin'
      get 'manage'
      post 'admin', to: 'job_postings#filter'
      post 'manage', to: 'job_postings#filter_manage'
      post 'job_postings', to: 'job_postings#filter_index'
    end
  end

  resources :job_applications, only: %i[show update destroy] do
    resource :job_posting_answers, only: %i[edit update destroy]
    resources :interviews, only: [:new]
    member do
      get 'select_resume'
      patch 'update_resume'
      get 'finalize'
      get 'hire'
      get 'decline'
    end
    collection do
      get 'user'
      post 'user', to: 'job_applications#filter_user'
    end
  end

  resources :interviews, only: %i[create edit update] do
    collection do
      get 'manage'
      get 'admin'
    end
  end

  resources :positions do
    collection do
      get 'admin'
    end
  end
end

app/models/job_posting.rb
# frozen_string_literal: true

class JobPosting < ApplicationRecord
  include Filterable

  scope :status, ->(status) { where status: status }
  scope :job_department, ->(department) { joins(job: :organization).where(organizations: { department: Organization.departments[department] }) }
  scope :job_type, ->(job_type) { joins(:job).where(jobs: { job_type: job_type }) }

  # Relationships
  # a job posting belongs to a job
  belongs_to :job, foreign_key: :job_id, dependent: :destroy
  # a job posting belongs to a user
  belongs_to :user, foreign_key: :creator_id

  # delete job applications if the related job posting is deleted
  has_many :job_applications, dependent: :destroy
  # delete job posting questions if the related job posting is deleted
  has_many :job_posting_questions, dependent: :destroy

  has_many :positions

  # different statuses for a job posting
  enum status: %i[waiting_approval draft open interviewing closed extension_pending]

  # Validations
  # make sure a job_id is present
  validates :job_id, presence: true
  # title must be minimum length of five characters
  validates :title, presence: true, length: { maximum: 100 }
  # description must be at least fifteen characters
  validates :description, presence: true, length: { minimum: 15, maximum: 4000 }
  validates :deadline, presence: true

  validates :start_date, presence: true
  validates :end_date, presence: true

  validate :end_date_cannot_be_before_start_date, :end_date_cannot_be_in_the_past

  # Remove to manual 'validations' as admins must approve postings, for greater flexibility
  # validate :deadline_cannot_be_in_the_past
  # validate :deadline_cannot_be_within_two_weeks

  accepts_nested_attributes_for :positions

  def active?
    status == 'open'
  end

  private

  def deadline_cannot_be_in_the_past
    errors.add(:deadline, 'cannot be in the past') if deadline < Date.today
  end

  def deadline_cannot_be_within_two_weeks
    two_weeks_later = Date.today + 2.weeks
    errors.add(:deadline, 'cannot be within 2 weeks') if deadline < two_weeks_later
  end

  def end_date_cannot_be_in_the_past
    if end_date.nil?
      false
    elsif end_date < Date.today
      errors.add(:end_date, 'cannot be in the past')
    end
  end

  def end_date_cannot_be_before_start_date
    if end_date.nil? || start_date.nil?
      false
    elsif end_date <= start_date
      errors.add(:end_date, "can't be before or the same day as the start date")
    end
  end
end

app/controllers/job_postings_controller.rb
# frozen_string_literal: true

class JobPostingsController < ApplicationController
  include UserHelper

  skip_authorize_resource only: %i[new filter_index filter filter_manage]

  load_and_authorize_resource

  # before any action gets fired set the job posting
  before_action :set_job_posting, only: %i[show destroy edit update approve withdraw interview close reopen]

  # define the helper for the controller
  helper :application

  # GET /job_postings
  def index
    @active_org_jobs = Job.joins(:organization).where(organizations: { status: 'active' })
    @open_job_postings =
      JobPosting
      .joins(:job)
      .where(status: 'open', jobs: { id: @active_org_jobs.ids })
      .filter(params.slice(:job_type, :job_department))
      .order(:deadline)
      .paginate(page: params[:page], per_page: 10)
  end

  # GET /job_postings/new?job_id=:id
  def new
    @jobposting = JobPosting.new
    if params[:job_id]
      @job = Job.find(params[:job_id])
      authorize! :manage, @job
    else
      redirect_to select_job_postings_path
    end
  end

  # GET /job_postings/select
  def select
    # only show the job postings the user can manage
    if superadmin?(current_user)
      @jobs = Job.joins(:organization).where(organizations: { status: 'active' })
    elsif can? :select, JobPosting
      @orgs = managed_orgs(current_user)
      @jobs = []
      @orgs.each do |org|
        org.jobs.each do |job|
          @jobs.push(job)
        end
      end
      # @jobs = @orgs.jobs
      # @jobs_without_postings = Job.includes(:job_posting).where(organization_id: Organization.joins(:jobs).where(jobs: { user_id: Position.where(user_id: current_user.id) }).where(job_postings: { job_id: nil }))
    end
    @jobs = @jobs
    # TODO: include closed job postings to be reopened
  end

  # POST /job_posting
  def create
    @jobposting = JobPosting.new(job_posting_params)
    if @jobposting.save
      flash[:success] = 'Job Posting Successfully Created!'
      redirect_to job_posting_job_posting_questions_path(@jobposting.id)
    else
      flash[:danger] = 'Could not create Job Posting <ul>'
      flash[:danger] << '<li>' + @jobposting.errors.full_messages.join('</li><li>')
      flash[:danger] << '</ul>'
      # render :new
      redirect_to action: 'new', job_id: @jobposting.job_id
    end
  end

  # GET /job_postings/:id
  def show
    if @job_posting.job.organization.status != 'active' && (current_user.role != 'management' || !superadmin?(current_user))
      flash[:warning] = 'The organization ' + @job_posting.job.organization.name + ' is not active, so its job postings cannot be viewed.'
      redirect_back(fallback_location: job_postings_path)
    else
      if @job_posting.status == 'open' || @job_posting.status == 'interviewing' || superadmin?(current_user) || managed_orgs(current_user).include?(@job_posting.job.organization)
        @job = Job.find_by! id: @jobposting.job_id
        @organization = Organization.find_by! id: @job.organization_id
      else
        flash[:warning] = 'Job posting ' + @job_posting.title + ' is currently not open, so cannot be viewed.'
        redirect_back(fallback_location: job_postings_path)
      end
    end
  end

  # GET /job_postings/:id/edit
  def edit
    if @jobposting.status != 'waiting_approval'
      flash[:danger] = "The Job Posting is currently not 'waiting approval', so cannot be created, deleted, or editted. Approval must first be revoked for the posting to be editable. Please contact an administrator if you require assistance."
      redirect_back(fallback_location: job_postings_path)
    else
      @jobposting = JobPosting.find(params[:id])
    end
  end

  # PUT /job_postings/:id
  def update
    @jobposting = JobPosting.find(params[:id])
    if @jobposting.update_attributes(job_posting_params)
      flash[:success] = 'Job Posting Successfully Updated!'
      redirect_to job_posting_job_posting_questions_path(@jobposting.id)
    else
      flash[:danger] = 'Could Not Update Job Posting!'
      flash[:danger] << '<li>' + @jobposting.errors.full_messages.join('</li><li>')
      flash[:danger] << '</ul>'
      redirect_to edit_job_posting_path(@jobposting)
    end
  end

  # DESTROY /job_postings/:id
  def destroy
    @jobposting.destroy
    flash[:success] = 'Job Posting Successfully Deleted!'
    redirect_to job_postings_path
  end

  # GET /job_postings/admin
  def admin
    @job_postings = JobPosting.filter(params.slice(:status)).order(:deadline).paginate(page: params[:page], per_page: 10)
  end

  # GET /job_postings/:id/approve
  def approve
    @jobposting.status = 'open'
    @jobposting.save
    redirect_back(fallback_location: job_postings_path)
  end

  # GET /job_postings/:id/withdraw
  def withdraw
    @jobposting.status = 'waiting_approval'
    @jobposting.save
    redirect_back(fallback_location: job_postings_path)
  end

  # GET /job_postings/:id/interview
  def interview
    if @jobposting.deadline.past?
      @jobposting.status = 'interviewing'
      @jobposting.save
    else
      flash[:danger] = 'Cannot begin interviewing process, job posting deadline has not passed.'
    end
    redirect_back(fallback_location: job_postings_path)
  end

  # GET /job_postings/:id/close
  def close
    flash[:success] = 'Job Posting Successfully Closed'
    @jobposting.status = 'closed'

    not_hired = @jobposting.job_applications.where.not(status: 'hired')
    not_hired.each do |nh|
      if nh.status == 'submitted'
        UserMailer.decline_job_application(nh).deliver_now
      end
    end
    not_hired.update_all status: 'declined'
    @jobposting.save
    redirect_to job_posting_job_applications_path(job_posting_id: @job_posting.id)
  end

  # GET /job_postings/:id/reopen
  def reopen
    flash[:success] = 'Job Posting Successfully Reopened, Now Waiting for Admin Approval'
    @jobposting.status = 'waiting_approval'
    @jobposting.job_applications.update_all archived: true
    @jobposting.save
    redirect_to job_posting_job_applications_path(job_posting_id: @job_posting.id)
  end

  # GET /job_postings/manage
  def manage
    @managing_jobs = Job.includes(:positions).where(positions: { user_id: current_user.id })
    @managed_orgs = Organization.includes(:jobs).where(jobs: { id: @managing_jobs.ids, role: %w[management admin] })
    @managed_jobs = Job.where(organization_id: @managed_orgs.ids)
    @managed_postings = JobPosting.where(job_id: @managed_jobs.ids).filter(params.slice(:status)).order('deadline').paginate(page: params[:page], per_page: 10)
  end

  def filter_index
    if params[:job_type] == 'All' && params[:job_department] == 'All'
      redirect_to job_postings_path
    elsif params[:job_type] != 'All' && params[:job_department] == 'All'
      redirect_to job_postings_path(job_type: params[:job_type])
    elsif params[:job_type] == 'All' && params[:job_department] != 'All'
      redirect_to job_postings_path(job_department: params[:job_department])
    else
      redirect_to job_postings_path(job_type: params[:job_type], job_department: params[:job_department])
    end
  end

  def filter
    if params[:status] == 'All'
      redirect_to admin_job_postings_path
    else
      redirect_to admin_job_postings_path(status: params[:status])
    end
  end

  def filter_manage
    if params[:status] == 'All'
      redirect_to manage_job_postings_path
    else
      redirect_to manage_job_postings_path(status: params[:status])
    end
  end

  private

  def job_posting_params
    params.require(:job_posting).permit(:creator_id, :title, :description, :job_id, :deadline, :status, :start_date, :end_date)
  end

  def set_job_posting
    @jobposting = JobPosting.find(params[:id])
  end
end

app/views/job_postings/_job_posting_interview_select_list_item.html.erb
<li class="list-group-item">

  <!-- show the job title and link to the job posting detail -->
  <h4 class="mb-sm">
    <%= link_to job_posting_job_applications_path(posting), class: "ripple" do %>
      <%= posting.title %>
    <% end %>
  </h4>

  <!-- display the application deadline -->
  <p class="text-soft">
    Application Deadline: <%= distance_of_time_in_words(Time.now, posting.deadline) %><br />
  </p>

  <% if posting.job_applications.any? %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th class="col-md-1">
            APP. ID
          </th>
          <th>
            SUBMITTED BY <abbr title="Hover to show submission time"><em class="ion-help-circled icon-fw"></em></abbr>
          </th>
          <th>
            STATUS
          </th>
          <% if can? :manage, JobApplication %>
          <th>
            ACTIONS
          </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% posting.job_applications.each do |app| %>
          <% if app.status == "submitted" %>
            <%= render 'job_applications/job_application', job_application: app %>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= link_to job_posting_job_applications_path(posting), class: "ripple" do %>
      <p class="text-right"><em>View All</em></p>
    <% end %>
  <% end %>

</li>

app/views/job_postings/_job_posting_list_item.html.erb
<li class="list-group-item">
  <!-- render the dropdown-->
  <%= render 'job_posting_list_item_dropdown', posting: posting %>

  <!-- show the job title and link to the job posting detail -->
  <h5 class="mb-sm">
    <%= link_to job_posting_path(posting), class: "ripple" do %>
      <%= posting.title %>
    <% end %>
  </h5>

  <!-- display the application deadline -->
  <p class="text-gray-darker">Application Deadline:
    <%= posting.deadline.strftime("%A, %b %d, %Y") %><% if posting.deadline.future? %> | <%= distance_of_time_in_words(Time.now, posting.deadline) %><% end %>
  </p>

  <p class="text-gray-darker">Organization: <%= link_to posting.job.organization.name, posting.job.organization %><br /></p>

  <p class="text-gray-darker">Term: <%= posting.start_date.to_date %> to <%= posting.end_date.to_date %><br /></p>

  <!-- display the truncated job posting description -->
  <p><%= h truncate(posting.description, :length => 270) %></p>

</li>

app/views/job_postings/_job_posting_list_item_dropdown.html.erb
<% if can? :manage, posting %>
  <div class="pull-right dropdown">
    <%= status_label(posting) %>
    <% if can? :approve_job_postings, posting %>
    <button type="button" data-toggle="dropdown" class="btn btn-default btn-flat btn-flat-icon"><em class="ion-android-more-vertical"></em></button>
    <ul role="menu" class="dropdown-menu md-dropdown-menu dropdown-menu-right">
      <li>
        <%= link_to "View Applicants", job_posting_job_applications_path(posting.id) %>
      </li>
      <% if superadmin?(current_user) %>
        <% if posting.status != "open" %>
          <li>
            <%= link_to "Approve Posting", approve_job_posting_path(posting) %>
          </li>
        <% else %>
          <li>
            <%= link_to "Withdraw Approval", withdraw_job_posting_path(posting) %>
          </li>
          <li>
            <%= link_to "Begin Interviewing", interview_job_posting_path(posting) %>
          </li>
        <% end %>
      <% else %>
        <% if posting.status == "open" %>
          <li>
            <%= link_to "Begin Interviewing", interview_job_posting_path(posting) %>
          </li>
        <% else %>
          <li>
            <%= link_to "Reopen Posting", approve_job_posting_path(posting) %>
          </li>
        <% end %>
      <% end %>
      <li>
        <%= link_to "Edit Posting", edit_job_posting_path(posting.id) %>
      </li>
      <% if superadmin?(current_user) %>
        <li>
          <%= link_to "Delete Posting", posting, method: :delete, data: { confirm: "Are you sure?" } %>
        </li>
      <% end %>
    </ul>
    <% end %>
  </div>
<% end %>

app/views/job_postings/_job_posting_list_item_dropdown_admin.html.erb
<% if can? :manage, posting %>
  <div class="pull-right dropdown">
    <%= status_label(posting) %>
    <% if can? :approve_job_postings, posting %>
    <button type="button" data-toggle="dropdown" class="btn btn-default btn-flat btn-flat-icon"><em class="ion-android-more-vertical"></em></button>
    <ul role="menu" class="dropdown-menu md-dropdown-menu dropdown-menu-right">
      <li>
        <%= link_to "View Applicants", job_posting_job_applications_path(posting.id) %>
      </li>
      <% if posting.status != "open" %>
        <li>
          <%= link_to "Approve Posting", approve_job_posting_path(posting) %>
        </li>
      <% else %>
        <li>
          <%= link_to "Withdraw Approval", withdraw_job_posting_path(posting) %>
        </li>
        <li>
          <%= link_to "Begin Interviewing", interview_job_posting_path(posting) %>
        </li>
      <% end %>
      <li>
        <%= link_to "Edit Posting", edit_job_posting_path(posting.id) %>
      </li>
      <li>
        <%= link_to "Delete Posting", posting, method: :delete, data: { confirm: "Are you sure?" } %>
      </li>
    </ul>
    <% end %>
  </div>
<% end %>

app/views/job_postings/_job_posting_overview.html.erb
<p class="lead">Job Posting Overview</p>
<hr />
<%= render 'job_postings/job_posting_list_item_dropdown', posting: @job_posting %>
<h5>
  <%= posting.title %>
</h5>
<p>
  Application Deadline: <%= distance_of_time_in_words(Time.now, posting.deadline) %> (<%= posting.deadline.to_date.strftime('%A, %B %d, %l:%M %p, %Y') %>)
</p>
<p>
  Organization: <%= link_to posting.job.organization.name, posting.job.organization %>
</p>
<p class="text-gray-darker">
  Term: <%= posting.start_date.to_date %> to <%= posting.end_date.to_date %><br />
</p>
<p>
  <%= simple_format(posting.description) %>
</p>

app/views/job_postings/_job_posting_reopen_button.html.erb
<%= link_to reopen_job_posting_path(posting), class: "btn btn-warning", :"data-html" => "true", :"data-toggle" => "popover", :"data-content" => "Close the job posting, and decline all applicants who were not hired.<br /><br /> Select this after the job has been filled.", :"data-title" => "Closing a Job Posting", :"data-trigger" => "hover", :"data-placement" => "bottom", data: { :confirm => "Are you sure you're finished with this job posting?" } do %>
  <em class="ion-android-checkmark-circle icon-lg mr-sm"></em>Reopen Job Posting
<% end %>

app/views/job_postings/_job_posting_status_button.html.erb
<% if posting.status != "closed" %>
  <%= link_to close_job_posting_path(posting), class: "btn btn-primary", :"data-html" => "true", :"data-toggle" => "popover", :"data-content" => "Close the job posting, and decline all applicants who were not hired.<br /><br /> Select this after the job has been filled.", :"data-title" => "Closing a Job Posting", :"data-trigger" => "hover", :"data-placement" => "auto", data: { :confirm => "Are you sure you're finished with this job posting?" } do %>
    <em class="ion-android-checkmark-circle icon-lg mr-sm"></em>Close Job Posting
  <% end %>
<% else %>
  <%= link_to reopen_job_posting_path(posting), class: "btn btn-warning", :"data-html" => "true", :"data-toggle" => "popover", :"data-content" => "Reopen the job posting, and archive all previous applicants.<br /><br /> Select this to restart the hiring process using the same job and job posting details.", :"data-title" => "Reopening a Job Posting", :"data-trigger" => "hover", :"data-placement" => "auto", data: { :confirm => "Are you sure you want to begin hiring for this job posting?" } do %>
    <em class="ion-android-checkmark-circle icon-lg mr-sm"></em>Reopen Job Posting
  <% end %>
<% end %>

app/views/job_postings/edit.html.erb
<!-- page title -->
<% content_for :title, "Edit Job Posting" %>

<!-- page content -->
<div class="container-fluid container-lg">
  <div class="card">
    <div class="card-body">
      <!-- render the job posting form -->
      <%= render 'job_posting_form' %>
    </div>
  </div>
</div>

app/views/job_postings/index.html.erb
<!-- define title for the page -->
<% content_for :title, "Job Postings" %>

<!-- main container for job postings -->
<div class="container-fluid container-lg">

  <!-- filtering header -->
  <div class="row mb">
    <div class="col-sm-12 text-right hidden-xs">
      <%= form_tag({controller: "job_postings", action: "filter_index"}, method: "post", class:"form-inline") do %>
        <div class="form-group">
          <% select_list = Job.job_types.keys.map { |w| [w.titleize, w] }.insert(0,"All") %>
          <% department_list = Organization.departments.keys.map { |w| [w.titleize, w] }.insert(0,"All") %>
          <%= label_tag 'Department', nil, class: 'mr' %>
          <%= select_tag :job_department, options_for_select(department_list, params[:job_department]), class: "form-control input-sm mr" %>
          <%= label_tag 'Type', nil, class: 'mr' %>
          <%= select_tag :job_type, options_for_select(select_list, params[:job_type]), class: "form-control input-sm" %>
          <%= submit_tag 'Filter', class: "ml btn btn-inverse" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
        <% if @open_job_postings.any? %>
          <ul class="list-group">
          <!-- iterate through all of the open job postings -->
          <% @open_job_postings.each do |posting| %>
            <%= render 'job_posting_list_item', posting: posting, status: true %>
          <% end %>
          </ul>
        <% else %>
          <p class="m-xl lead text-center">Could not find any open jobs.</p>
        <% end %>
      <% if @open_job_postings.count >= 10 %>
        <center><%= will_paginate @open_job_postings, renderer: BootstrapPagination::Rails, page_links: false %><br /></center>
      <% end %>
    </div>
  </div>
</div>

app/views/job_postings/manage.html.erb
<!-- page title -->
<% content_for :title, "Manage Job Postings" %>

  <!-- main container for job postings -->
  <div class="container-lg container-fluid">

    <!-- filtering header -->
    <div class="row mb">
      <div class="col-sm-4">
        <%= link_to(new_job_posting_path, class: "btn btn-primary") do %>
          <em class="ion-plus mr-sm"></em>Create Job Posting
        <% end %>
      </div>
      <div class="col-sm-8 text-right hidden-xs">
        <%= form_tag({controller: "job_postings", action: "filter_manage"}, method: "post", class:"form-inline") do %>
          <div class="form-group">
            <% select_list = JobPosting.statuses.keys.map { |w| [w.titleize, w] }.insert(0,"All") %>
            <%= label_tag 'Status', nil, class: 'mr' %>
            <%= select_tag :status, options_for_select(select_list, params[:status]), class: "form-control input-sm" %>
            <%= submit_tag 'Filter', class: "ml btn btn-inverse" %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- list of job postings -->
    <div class="card">
      <div class="card-body">
        <ul class="list-group">
          <% if @managed_postings.any? %>
            <% @managed_postings.each do |posting| %>
              <%= render 'job_posting_list_item', posting: posting, dropdown: true %>
            <% end %>
          <% else %>
            <p class="m-xl lead text-center">Cannot find any job postings.</p>
          <% end %>
        </ul>
      </div>

      <% if @managed_postings.count >= 10 %>
        <!-- show the paginator for the will_paginate gem -->
        <center><%= will_paginate @open_job_postings, renderer: BootstrapPagination::Rails, page_links: false %><br /></center>
      <% end %>

    </div>
  </div>

app/views/job_postings/new.html.erb
<!-- page title -->
<% content_for :title, "New Job Posting" %>

<!-- page content -->
<div class="container-fluid container-lg">
  <div class="card">
    <div class="card-body">
      <!-- render the job posting form -->
      <%= render 'job_posting_form' %>
    </div>
  </div>
</div>

app/views/job_postings/select.html.erb
<% content_for :title, "Select Job" %>


<div class="container-fluid container-lg">
  <div class="row">
    <div class="card">
      <div class="card-heading">
        <h4>Jobs <br>
        <small>Jobs for your active organizations</small></h4>
      </div>
      <div class="">
        <% if @jobs.any? %>
          <div class="table-responsive">
            <table class="table table-hover">
              <tbody>
                <% @jobs.each do |job| %>
                  <tr class="">
                    <td class=""><%= link_to job.title, job %></td>
                    <td class=""><%= link_to job.organization.name, job.organization %></td>
                    <td class=""><%= job.description %></td>
                    <td class="">
                      <% if JobPosting.where(:job_id => job.id).exists? %>
                        <% jp = JobPosting.find_by(:job_id => job.id) %>
                        <% case jp.status %>
                        <% when "open" %>
                          <%= link_to "View Job Posting", job_posting_path(:id => jp), class: "align-center btn btn-flat btn-success" %>
                        <% when "waiting_approval" || "extension_pending" %>
                          <%= link_to "View Job Posting", job_posting_path(:id => jp), class: "align-center btn btn-flat btn-warning" %>
                        <% when "interviewing" %>
                          <%= link_to "View Job Posting", job_posting_path(:id => jp), class: "align-center btn btn-flat btn-info" %>
                        <% when "closed" %>
                          <%= link_to "View Job Posting", job_posting_path(:id => jp), class: "align-center btn btn-flat btn-danger" %>
                        <% end %>
                      <% else %>
                        <%= link_to "Create Job Posting", new_job_posting_path(:job_id => job.id), class: "align-center btn btn btn-primary" %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% else %>
          <p class="text-center">
            Currently No Jobs to create posting for.
            <br>
            <%= link_to "View My Organizations", user_organizations_path, class: "align-center btn btn btn-primary mv" %>
          </p>
        <% end %>
      </div>
    </div>
    <div class="text-center">
      <%= link_to "Create New Job", new_organization_job_path(:organization_id => @jobs.first.organization.id) %>
    </div>
  </div>
</div>

app/views/job_postings/show.html.erb
<% content_for :title, "Job Postings" %>

<div class="container container-lg">
  <div class="card">
    <div class="card-body">
      <!-- render the dropdown-->
      <%= render 'job_posting_list_item_dropdown', posting: @jobposting %>
      <p class="lead"><%= link_to @job.title, job_path(:id => @job.id) %></p>
      <hr />
      <p>
        Application Deadline:
        <% if @jobposting.deadline.past? %>
          <%= @jobposting.deadline.to_date %>
        <% else %>
          in <%= distance_of_time_in_words(Time.now, @jobposting.deadline) %> (<%= @jobposting.deadline.to_date %>)
        <% end %>
      </p>
      <p>
        Organization: <%= link_to @organization.name, @organization %>
      </p>
      <p>
        Term: <%= @jobposting.start_date.to_date %> to <%= @jobposting.end_date.to_date %>
      </p>
      <p>
        <small>Last Updated: <%= @jobposting.updated_at.strftime("%A, %b %d, %Y, %l:%M %p") %>
        </small>
      </p>
      <div class="container container-sm reader-block">
        <p class="mv-lg">
          <%= simple_format(@jobposting.description) %>
        </p>
      </div>
    </div>

    <div class="card-footer">
      <%= link_to "Apply Now", new_job_posting_job_application_path(@jobposting.id), :class =>"btn btn-flat btn-primary btn-block" %>
    </div>
  </div>
</div>