config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Take advantage of shallow routing wherever possible:
  # :index, :new, :create should be nested with parent resource
  # :show, :edit, :update, :destroy should be unnested

  root                     'static_pages#home'
  get   'about'        =>  'static_pages#about'
  get   'contact'      =>  'static_pages#contact'
  get   'develop'      =>  'static_pages#develop'

  ####################################################
  # Profiles
  # devise routes for authentication
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'registrations' }
  resources :profiles, controller: 'users' do
    resources :resumes, only: %i[index create destroy]
    get 'settings'
  end

  ####################################################
  # Organizations
  resources :organizations do
    member do
      get 'approve'
      get 'withdraw'
      get 'archive'
    end
    collection do
      get 'admin'
      get 'manage'
      get 'user'
      post 'admin', to: 'organizations#filter'
      post 'manage', to: 'organizations#filter_manage'
      post 'organizations', to: 'organizations#filter_index'
      post 'user', to: 'organizations#filter_user'
    end
    resources :jobs, only: %i[new create]
  end

  ####################################################
  # Jobs
  resources :jobs, only: %i[show edit update destroy] do
    member do
      get 'assign'
      post 'create_position'
      put 'add_user'
    end
  end

  resources :job_postings do
    resources :job_posting_questions, only: %i[index create update destroy]
    resources :job_applications, only: %i[index new create] do
      resource :job_posting_answers, only: %i[new create]
    end
    member do
      get 'approve'
      get 'withdraw'
      get 'interview'
      get 'close'
      get 'reopen'
    end
    collection do
      get 'select'
      get 'admin'
      get 'manage'
      post 'admin', to: 'job_postings#filter'
      post 'manage', to: 'job_postings#filter_manage'
      post 'job_postings', to: 'job_postings#filter_index'
    end
  end

  resources :job_applications, only: %i[show update destroy] do
    resource :job_posting_answers, only: %i[edit update destroy]
    resources :interviews, only: [:new]
    member do
      get 'select_resume'
      patch 'update_resume'
      get 'finalize'
      get 'hire'
      get 'decline'
    end
    collection do
      get 'user'
      post 'user', to: 'job_applications#filter_user'
    end
  end

  resources :interviews, only: %i[create edit update] do
    collection do
      get 'manage'
      get 'admin'
    end
  end

  resources :positions do
    collection do
      get 'admin'
    end
  end
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  include Filterable

  scope :status, ->(status) { where status: status }
  scope :department, ->(department) { where department: department }
  # This scope needs a rewrite since the introduction of Positions through model
  # scope :user_managed, -> (current_user) { includes(:jobs).where(jobs: { :user_id => current_user.id, :role => ["management", "admin"] })}

  # Relationships
  # an organization has many jobs, delete if organization is also deleted
  has_many :jobs, dependent: :destroy
  # an organization has many users through their jobs, many to many
  has_many :users, through: :jobs

  # set the scope when performing actions
  default_scope -> { order(name: :asc) }

  # type of organizations with the engineering society
  enum department: %i[
    conferences
    design_teams
    services
    clubs
    events
    communications
    internal_affairs
    academics
    community_outreach
    science_formal
    first_year
    orientation_week
    human_resources
    professional_development
    finance
    information_technology
    engineering_review_board
    directors
  ]

  # db declaration defaults to 0
  enum status: %i[waiting_approval active archived]

  # Validations
  # make sure the name is present and is unique
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  # make sure the email is present and is unique
  validates :email, presence: true, uniqueness: true
  # set bounds and make sure unique description
  validates :description, presence: true, length: { minimum: 10, maximum: 4000 }
  validates :department, presence: true

  accepts_nested_attributes_for :jobs
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  load_and_authorize_resource

  skip_authorize_resource only: %i[filter_index filter_user]

  before_action :set_organization, only: %i[show destroy edit update approve withdraw archive]

  # GET /organizations
  def index
    @organizations = Organization.where(status: 'active').filter(params.slice(:department)).paginate(page: params[:page], per_page: 20)
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # POST /organizations
  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      flash[:success] = 'Organization Successfully Created!'
      redirect_to controller: 'organizations', action: 'show', id: @organization.id
    else
      render 'new'
    end
  end

  # GET /organizations/:id
  def show
    if @organization.status != 'active' && !superadmin(current_user)
      flash[:danger] = 'This organization is currently not open (has not been approved or has been archived), and therefore cannot be viewed. Please contact support if you feel this has been done in error.'
      redirect_back(fallback_location: organizations_path)
    end
    @jobs = @organization.jobs.order(role: :desc, title: :asc)
  end

  # GET /organizations/:id/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # PUT /organizations/:id
  def update
    if @organization.update_attributes(organization_params)
      flash[:success] = 'Organization Successfully Updated!'
      redirect_to controller: 'organizations', action: 'show', id: @organization.id
    else
      render 'edit'
    end
  end

  # DELETE /organizations/:id
  def destroy
    @organization.destroy
    flash[:success] = 'Organization Successfully Deleted!'
    redirect_to organizations_url
  end

  # GET /organizations/admin
  def admin
    @organizations = Organization.filter(params.slice(:status, :department)).paginate(page: params[:page], per_page: 10)
  end

  # GET /organizations/user
  def user; end

  # GET /organizations/:id/approve
  def approve
    @organization.status = 'active'
    @organization.save
    redirect_to admin_organizations_path
  end

  # GET /organizations/:id/withdraw
  def withdraw
    @organization.status = 'waiting_approval'
    @organization.save
    redirect_to admin_organizations_path
  end

  # GET /organizations/:id/archive
  def archive
    @organization.status = 'archived'
    @organization.save
    redirect_to admin_organizations_path
  end

  def filter
    if params[:status] == 'All' && params[:department] == 'All'
      redirect_to admin_organizations_path
    elsif params[:status] != 'All' && params[:department] == 'All'
      redirect_to admin_organizations_path(status: params[:status])
    elsif params[:status] == 'All' && params[:department] != 'All'
      redirect_to admin_organizations_path(department: params[:department])
    else
      redirect_to admin_organizations_path(status: params[:status], department: params[:department])
    end
  end

  def filter_manage
    if params[:status] == 'All' && params[:department] == 'All'
      redirect_to manage_organizations_path
    elsif params[:status] != 'All' && params[:department] == 'All'
      redirect_to manage_organizations_path(status: params[:status])
    elsif params[:status] == 'All' && params[:department] != 'All'
      redirect_to manage_organizations_path(department: params[:department])
    else
      redirect_to manage_organizations_path(status: params[:status], department: params[:department])
    end
  end

  def filter_index
    if params[:department] == 'All'
      redirect_to organizations_path
    else
      redirect_to organizations_path(department: params[:department])
    end
  end

  def filter_user
    if params[:department] == 'All'
      redirect_to user_organizations_path
    else
      redirect_to user_organizations_path(department: params[:department])
    end
  end

  def manage
    @managing_jobs = Job.includes(:positions).where(positions: { user_id: current_user.id })
    @managed_organizations = Organization.includes(:jobs).where(jobs: { id: @managing_jobs.ids, role: %w[management admin] }).filter(params.slice(:status, :department)).paginate(page: params[:page], per_page: 10)
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :description, :email, :status, :department)
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end
end

app/helpers/organizations_helper.rb
# frozen_string_literal: true

module OrganizationsHelper
end

app/views/organizations/_active_job_postings.html.erb
<tr>
  <td>
    <%= link_to job_posting.title.titleize, job_path(:id => job_posting.job_id) %>
  </td>
  <td>
    <%= job_posting.deadline.to_date %>
    <% if !job_posting.deadline.past? %>
    (<em><%= distance_of_time_in_words(Time.now, job_posting.deadline) %> left</em>)
    <% end %>
  </td>
  <td>
    <% if job_posting.job.role == "management" %>
      Managerial Position
    <% elsif job_posting.job.role == "admin" %>
      Administration Position
    <% elsif job_posting.job.role == "regular" %>
      General Member Position
    <% end %>
  </td>
  <td>
    <%= job_posting.job.job_type.titleize %>
  </td>
  <td>
    <%= link_to "View Job Posting", job_posting_path(:id => job_posting.id) %>
  </td>
  <td>
    <%= link_to "Apply Now", new_job_posting_job_application_path(job_posting.id) %>
  </td>
</tr>

app/views/organizations/_active_job_postings_table.html.erb
<div class="table-responsive mh">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Deadline</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
        <% if job.job_posting.present? && job.job_posting.status == "open" %>
          <%= render "active_job_postings", :job_posting => job.job_posting %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/organizations/_active_positions.html.erb
<% if job.positions.any? %>
  <% job.positions.each do |pos| %>
    <% if pos.active? %>
      <tr>
        <td>
          <%= link_to pos.job.title.titleize, job_path(:id => job.id) %>
        </td>
        <td>
          <%= link_to pos.user.first_name.to_s + " " + pos.user.last_name.to_s, profile_path(pos.user.id) %>
        </td>
        <td>
          <%= pos.user.email %>
        </td>
        <td>
          <% if pos.job.role == "management" %>
            <span class="text-success">Managerial Position</span>
          <% elsif pos.job.role == "admin" %>
            Administration Position
          <% elsif pos.job.role == "regular" %>
            General Member Position
        <% end %>
        </td>
        <td>
          <%= pos.job.job_type.titleize %>
        </td>
        <td>
          <%= pos.start_date.to_date %>
        </td>
        <td>
          <%= pos.end_date.to_date %>
        </td>
      </tr>
    <% end %>
  <% end %>
<% end %>

app/views/organizations/_active_positions_table.html.erb
<div class="table-responsive mh">
  <table class="table table-hover">
    <tbody>
      <% @jobs.each do |job| %>
        <%# displays all active positions as well as jobs with job postings %>
        <%= render "active_positions", :job => job %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/organizations/_admin_index.html.erb
<% content_for :title, " / Manage Organizations" %>

<div class="container container-fluid">

  <div class="container-fluid container-md">
    <h5>Create an Organization</h5>
    <div class="card">
      <div class="card-body">
        <%= form_for(@organization) do |f| %>
          <%= render 'shared/organization_error_messages' %>

          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>

          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control', style: 'resize:none' %>

          <%= f.label :users %>
          <%= select_tag "organization_users", options_from_collection_for_select(User.all, 'id', 'first_name',@organization.users.map { |j| j.id }), :multiple => true %>

          <hr>

          <%= f.submit "Create Organization", class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/organizations/_jobs_table.html.erb
<% if @organization.jobs.any? %>
  <div class="table-responsive mh">
    <table class="table table-hover">
      <tbody>
        <%= render @jobs %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="alert alert-warning mv mh">
    There are currently no jobs in this organization.
  </div>
<% end %>

app/views/organizations/_organization_form.html.erb
<%= form_for @organization, :html => {:class => 'form-horizontal'} do |f| %>
  <!-- render any error messages -->
  <%= render 'shared/organization_error_messages' %>

  <!-- form fields -->
  <!-- name -->
  <fieldset class="last-child">
    <div class="form-group">
      <%= f.label :name, class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
  </fieldset>

  <!-- email -->
  <fieldset class="last-child">
    <div class="form-group">
      <%= f.label :email, class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
        <%= f.text_field :email, class: 'form-control' %>
      </div>
    </div>
  </fieldset>

  <!-- description -->
  <fieldset>
    <div class="form-group">
      <%= f.label :description, class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
        <%= f.text_area :description, class: 'form-control', rows: "8", style: 'resize:none' %>
      </div>
    </div>
  </fieldset>

  <!-- status -->
  <% if can? :manage, Organization %>
    <fieldset>
      <div class="row">
      <%= f.label :status, class: "col-sm-1 control-label" %>
        <!-- only admins are able to set the status -->
        <div class="col-sm-11">
            <%= f.select :status, Organization.statuses.keys.map { |w| [w.titleize, w] }, {}, {class: "form-control"} %>
        </div>
      </div>
    </fieldset>
  <% end %>

  <!-- department -->
  <fieldset class="last-child">
    <div class="row">
      <%= f.label :department, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.select :department, Organization.departments.keys.map { |w| [w.titleize, w] }, {:include_blank => "Select Department", :selected => 0}, {class: "form-control"} %>
        </div>
    </div>
  </fieldset>

  <hr>

  <!-- submit button -->
  <% if action_name == 'edit' %>
    <%= f.submit "Edit Organization", class: "btn btn-primary btn-block" %>
  <% else %>
    <%= f.submit "Create Organization", class: "btn btn-primary btn-block" %>
  <% end %>
  <%= link_to "Cancel",root_path, class: "btn btn-inverse btn-block" %>
<% end %>

app/views/organizations/_organization_list_item_dropdown.html.erb
<!-- if user has the permissions to manage organizations show the dropdown -->
<% if can? :manage, organization %>
  <div class="pull-right dropdown">

    <!-- status label, if passed parameter is true -->
    <% if status %>
      <%= status_label_organization(organization) %>
    <% end %>

    <!-- role label, if passed parameter is true -->
    <% if role %>
      <%= role_label_organization(organization) %>
    <% end %>

    <!-- dropdown button -->
    <button type="button" data-toggle="dropdown" class="btn btn-default btn-flat btn-flat-icon"><em class="ion-android-more-vertical"></em></button>

    <!-- menu list -->
    <ul role="menu" class="dropdown-menu md-dropdown-menu dropdown-menu-right">
      <% if can? :manage, :all %>
        <% if organization.status != "archived"  %>
          <% if organization.status == "waiting_approval" %>
            <li>
              <%= link_to "Approve Organization", approve_organization_path(organization) %>
            </li>
          <% else %>
            <li>
              <%= link_to "Archive Organization", archive_organization_path(organization) %>
            </li>
            <li>
              <%= link_to "Withdraw Approval", withdraw_organization_path(organization) %>
            </li>
          <% end %>
        <% else %>
          <li>
            <%= link_to "Unarchive Organization", withdraw_organization_path(organization) %>
          </li>
        <% end %>
          <li>
            <%= link_to "Delete Organization", organization, method: :delete,
              data: { confirm: "Are you sure?" } %>
          </li>
        <% end %>
          <li>
            <%= link_to "Create New Job", new_organization_job_path(organization.id) %>
          </li>
          <li>
            <%= link_to "Edit Organization", edit_organization_path(organization.id) %>
          </li>
    </ul>
  </div>
<% end %>

app/views/organizations/admin.html.erb
<!-- page title -->
<% content_for :title, "Admin Organizations" %>

<!-- page container -->
<div class="container-fluid container-lg">

    <!-- filtering header -->
    <div class="row mb">
      <div class="col-sm-4">
        <%= link_to(new_organization_path, class: "btn btn-primary") do %>
          <em class="ion-plus mr-sm"></em>Create Organization
        <% end %>
      </div>
      <div class="col-sm-8 text-right hidden-xs">
        <%= form_tag({controller: "organizations", action: "filter"}, method: "post", class:"form-inline") do %>
          <div class="form-group">
            <% select_list = Organization.statuses.keys.map { |w| [w.titleize, w] }.insert(0,"All") %>
            <% department_list = Organization.departments.keys.map { |w| [w.titleize, w] }.insert(0,"All") %>
            <%= label_tag 'Department', nil, class: 'mr' %>
            <%= select_tag :department, options_for_select(department_list, params[:department]), class: "form-control input-sm mr" %>
            <%= label_tag 'Status', nil, class: 'mr' %>
            <%= select_tag :status, options_for_select(select_list, params[:status]), class: "form-control input-sm" %>
            <%= submit_tag 'Filter', class: "ml btn btn-inverse" %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- list of organization -->
    <div class="card">
      <div class="card-body">
        <ul class="list-group">
          <% if @organizations.any? %>
            <% @organizations.each do |organization| %>
              <%= render 'organization_list_item', organization: organization, status: true, role: true %>
            <% end %>
          <% else %>
            <p class="lead text-center m-xl">Cannot find any organizations.</p>
          <% end %>
        </ul>
      </div>

      <% if @organizations.count >= 10 %>
        <!-- show the paginator for the will_paginate gem -->
        <center><%= will_paginate @open_job_postings, renderer: BootstrapPagination::Rails, page_links: false %><br /></center>
      <% end %>

  </div>
</div>

app/views/organizations/edit.html.erb
<!-- page title -->
<% content_for :title, "Edit " + @organization.name %>

<!-- page content -->
<div class="container-fluid container-lg">
  <div class="card">
    <div class="card-body">
      <!-- render the organization form -->
      <%= render 'organization_form' %>
    </div>
  </div>
</div>

app/views/organizations/manage.html.erb
<!-- page title -->
<% content_for :title, "Manage Organizations" %>

<!-- page container -->
<div class="container-fluid container-lg">

    <!-- filtering header -->
    <div class="row mb">
      <div class="col-sm-12 text-right hidden-xs">
        <%= form_tag({controller: "organizations", action: "filter_manage"}, method: "post", class:"form-inline") do %>
          <div class="form-group">
            <% select_list = Organization.statuses.keys.map { |w| [w.titleize, w] }.insert(0,"All") %>
            <% department_list = Organization.departments.keys.map { |w| [w.titleize, w] }.insert(0,"All") %>
            <%= label_tag 'Department', nil, class: 'mr' %>
            <%= select_tag :department, options_for_select(department_list, params[:department]), class: "form-control input-sm mr" %>
            <%= label_tag 'Status', nil, class: 'mr' %>
            <%= select_tag :status, options_for_select(select_list, params[:status]), class: "form-control input-sm" %>
            <%= submit_tag 'Filter', class: "ml btn btn-inverse" %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- list of organizations -->
    <div class="card">
      <div class="card-body">
        <ul class="list-group">
          <% if @managed_organizations.any? %>
            <% @managed_organizations.each do |organization| %>
              <%= render 'organization_list_item', organization: organization, status: true, role: true %>
            <% end %>
          <% else %>
            <p class="m-xl lead text-center">Cannot find any organizations.</p>
          <% end %>
        </ul>
      </div>

      <% if @managed_organizations.count > 9 %>
        <!-- show the paginator for the will_paginate gem -->
        <center><%= will_paginate @open_job_postings, renderer: BootstrapPagination::Rails, page_links: false %><br /></center>
      <% end %>

    </div>
</div>

app/views/organizations/new.html.erb
<!-- page title -->
<% content_for :title, "New Organization" %>

<!-- page content -->
<div class="container-fluid container-lg">
  <div class="card">
    <div class="card-body">
      <!-- render the organization form -->
      <%= render 'organization_form' %>
    </div>
  </div>
</div>

app/views/organizations/show.html.erb
<!-- page title -->
<% content_for :title, "Organization Overview: " + @organization.name %>

<div class="container container-fluid">
  <div class="card">
    <div class="card-body">
      <!-- render the dropdown -->
      <%= render 'organization_list_item_dropdown', organization: @organization, status: true, role: true %>
      <p class="lead">
        <span class="text-lg"><%= @organization.name %></span>
        <br><span class="text-muted"><small><%= @organization.email %></small></span>
      </p>
      <hr />
      <p>
        <%= simple_format(@organization.description) %>
      </p>
    </div>
  </div>

  <% if @jobs.any? && JobPosting.where(:job_id => @jobs.ids, :status => "open").exists? %>
    <div class="card">
      <div class="card-body">
        <% if can? :manage, @organization %>
          <%= link_to(new_job_posting_path, class: "btn btn-primary pull-right") do %>
            <em class="ion-plus mr-sm"></em>Create Posting
          <% end %>
        <% end %>
        <p class="lead">Active Job Postings</p>
        <div class="row" id="jobs">
          <%= render "active_job_postings_table" %>
        </div>
      </div>
    </div>
  <% end %>

  <% if @jobs.any? && position = Position.where(:job_id => @jobs.ids).exists? %>
    <div class="card">
      <div class="card-body">
        <p class="lead">Active Positions</p>
        <div class="row" id="jobs">
          <%= render "active_positions_table" %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">
      <% if can? :manage, @organization %>
        <%= link_to(new_organization_job_path(@organization.id), class: "btn btn-primary pull-right") do %>
          <em class="ion-plus mr-sm"></em>Add Job
        <% end %>
      <% end %>
      <p class="lead">All Jobs</p>
      <div class="row" id="jobs">
        <%= render "jobs_table" %>
      </div>
    </div>
  </div>

  <div class="ml button">
    <%= link_to raw("<em class='ion-arrow-left-a'></em> Back to Organizations"), organizations_path, class: "btn btn-primary" %>
  </div>

</div>

app/views/organizations/user_organizations.html.erb
<% content_for :title, "My Organizations" %>

<!-- container for the page -->
<div class="container container-fluid">

  <!-- add search bar -->
  <div class="mb-lg">
    <form role="form">
      <div class="mda-form-control">
        <input type="text" placeholder="Search Organization Title, Department, etc..." class="form-control input-lg">
      </div>
    </form>
  </div>

  <!-- main container for job postings -->
  <div class="container-fluid container-md">
      <div class="card">
        <div class="card-body">
          <ul class="list-group">
            <% if current_user.organizations.count == 0 %><br /><br />
              <p class="lead text-center">You are not apart of any organizations.</p>
            <% else %>
              <!-- iterate through all of user's orgs -->
              <% current_user.organizations.each do |organization| %>
                <%= render 'organization_list_item', organization: organization, dropdown: false %>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>

      </div>
    </div>